[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"SessionRX600_E1_E20_SYSTEM" 
[CONFIGURATIONS]
"Blinky" 
"Debug" 
"Debug-with-optimisation" 
[CURRENT_CONFIGURATION]
"Blinky" 
[CURRENT_SESSION]
"SessionRX600_E1_E20_SYSTEM" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_Blinky]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Blinky]
"SessionRX600_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Debug]
"SessionRX600_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_Debug-with-optimisation]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Debug-with-optimisation]
"SessionRX600_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_SESSION_Blinky_SessionRX600_E1_E20_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug-with-optimisation_SessionRX600_E1_E20_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_SessionRX600_E1_E20_SYSTEM]
[GENERAL_DATA_SESSION_SessionRX600_E1_E20_SYSTEM]
[END]
