# tests

MDIRS = \
	oarg \
	oconst \
	oconversion \
	olocal \
	onamedglob \
	onamedloc \
	opackageel \
	oreftonamed \
	oreftopackageel \
	oreturn

# FULL

TOP= ../../../../../..
include $(TOP)/Makefile.switch
