execUserReset()
{
  __writeMemory32(0x00000000, 0xE000ED08, "Memory"); //Vector table remap at 0x00000000
}

execUserPreload()
{
  // If the MAM values was wrong, a dummy read is necessary to get the flash memory in sync.
  __writeMemory32(0x00000001, 0x400FC040, "Memory"); // MEMMAP = 1
  __readMemory32(0x00000000, "Memory");
  __writeMemory32(0x00000000, 0xE000ED08, "Memory"); //Vector table remap at 0x00000000
}

