[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"DefaultSession" 
"SessionRX200_E1_E20_SYSTEM" 
[CONFIGURATIONS]
"Blinky" 
"Debug" 
"Debug_with_optimisation" 
[CURRENT_CONFIGURATION]
"Debug" 
[CURRENT_SESSION]
"SessionRX200_E1_E20_SYSTEM" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_Blinky]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Blinky]
"DefaultSession" 
"SessionRX200_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Debug]
"DefaultSession" 
"SessionRX200_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_Debug_with_optimisation]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Debug_with_optimisation]
"DefaultSession" 
"SessionRX200_E1_E20_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_with_optimisation_SessionRX200_E1_E20_SYSTEM]
[GENERAL_DATA_SESSION_SessionRX200_E1_E20_SYSTEM]
[GENERAL_DATA_SESSION_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Blinky_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Blinky_SessionRX200_E1_E20_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_with_optimisation_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_SessionRX200_E1_E20_SYSTEM]
[END]
