
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xadcps.h"

/*
* The configuration table for devices
*/

XAdcPs_Config XAdcPs_ConfigTable[] =
{
	{
		XPAR_PS7_XADC_0_DEVICE_ID,
		XPAR_PS7_XADC_0_BASEADDR
	}
};


