COMPILER=
ARCHIVER=
CP=cp
COMPILER_FLAGS=
EXTRA_COMPILER_FLAGS=
LIB=libxil.a

RELEASEDIR=../../../lib
INCLUDEDIR=../../../include
INCLUDES=-I${INCLUDEDIR}

OUTS = *.o

LIBSOURCES=*.c
INCLUDEFILES=*.h

libs:
	echo "Compiling cpu_cortexa53"

.PHONY: include
include:
	${CP} $(INCLUDEFILES) $(INCLUDEDIR)
