# functional

MDIRS = \
	arithmetic \
	bfield \
	constant \
	control \
	descriptor \
	logic \
	manipulation \
	name \
	reference \
	region \
	synchronization \
	table \
	external

# extern local FULL

TOP= ../../../..
include $(TOP)/Makefile.switch
