/*  THIS FILE WAS GENERATED BY THE DATALIGHT RELIANCE EDGE CONFIGURATION
    UTILITY.  DO NOT MODIFY.
*/
/** @file
*/
#include <redconf.h>
#include <redtypes.h>
#include <redmacs.h>
#include <redvolume.h>


const VOLCONF gaRedVolConf[REDCONF_VOLUME_COUNT] =
{
    { 512U, 65536U, false, 256U, "" }
};
