[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"Release session" 
"Simulator" 
[CONFIGURATIONS]
"Debug" 
"Release" 
[CURRENT_CONFIGURATION]
"Release" 
[CURRENT_SESSION]
"Release session" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Debug]
"Release session" 
"Simulator" 
[GENERAL_DATA_CONFIGURATION_Release]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Release]
"Release session" 
"Simulator" 
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_Simulator]
[GENERAL_DATA_SESSION_Release session]
[GENERAL_DATA_CONFIGURATION_SESSION_Release_Release session]
[GENERAL_DATA_CONFIGURATION_SESSION_Release_Simulator]
[GENERAL_DATA_SESSION_Simulator]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_Release session]
[END]
