#ifndef _HARDWARE_PLATFORM_DEFS_H_
#define _HARDWARE_PLATFORM_DEFS_H_

#define NUM_CORES  2u
#define NUM_DMA_CHANNELS 12u
#define NUM_IRQS 32u
#define NUM_PIOS 2u
#define NUM_PIO_STATE_MACHINES 4u
#define NUM_PWM_SLICES 8u
#define NUM_SPIN_LOCKS 32u
#define NUM_UARTS 2u
#define NUM_BANK0_GPIOS 30u

#define PIO_INSTRUCTION_COUNT 32u

#define XOSC_MHZ 12u


#ifndef PICO_STACK_SIZE
#define PICO_STACK_SIZE 2048u
#endif

#ifndef PICO_HEAP_SIZE
#define PICO_HEAP_SIZE 2048u
#endif

#ifndef PICO_NO_RAM_VECTOR_TABLE
#define PICO_NO_RAM_VECTOR_TABLE 0
#endif

#ifndef PICO_FLASH_SIZE_BYTES
#define PICO_FLASH_SIZE_BYTES (2 * 1024 * 1024)
#endif

#endif

