/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Sun, Dec 27, 2009                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
#pragma stacksize 0x400         /* Do not modify this line. */
