/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  RTOSDemo                                       */
/*      FILE         :  interrupt_handlers.c                           */
/*      DESCRIPTION  :  Interrupt Handler                              */
/*      CPU SERIES   :  RL78 - G14                                     */
/*      CPU TYPE     :  R5F104PJ                                       */
/*  													               */
/*      This file is generated by e2studio.                        */
/*  													               */
/***********************************************************************/                                                                       
                                                                                   
#include "interrupt_handlers.h"

/*
 * INT_SRO/INT_WDTI (0x4)
 */
void INT_WDTI (void) { }
//void INT_SRO (void) { }

/*
 * INT_LVI (0x6)
 */
void INT_LVI (void) { }

/*
 * INT_P0 (0x8)
 */
void INT_P0 (void) { }

/*
 * INT_P1 (0xA)
 */
void INT_P1 (void) { }

/*
 * INT_P2 (0xC)
 */
void INT_P2 (void) { }

/*
 * INT_P3 (0xE)
 */
void INT_P3 (void) { }

/*
 * INT_P4 (0x10)
 */
void INT_P4 (void) { }

/*
 * INT_P5 (0x12)
 */
void INT_P5 (void) { }

/*
 * INT_CSI20/INT_IIC20/INT_ST2 (0x14)
 */
void INT_ST2 (void) { }
//void INT_CSI20 (void) { }
//void INT_IIC20 (void) { }

/*
 * INT_CSI21/INT_IIC21/INT_SR2 (0x16)
 */
void INT_SR2 (void) { }
//void INT_CSI21 (void) { }
//void INT_IIC21 (void) { }

/*
 * INT_SRE2/INT_TM11H (0x18)
 */
void INT_TM11H (void) { }
//void INT_SRE2 (void) { }

/*
 * INT_CSI00/INT_IIC00/INT_ST0 (0x1E)
 */
void INT_ST0 (void) { }
//void INT_CSI00 (void) { }
//void INT_IIC00 (void) { }

/*
 * INT_CSI01/INT_IIC01/INT_SR0 (0x20)
 */
void INT_SR0 (void) { }
//void INT_CSI01 (void) { }
//void INT_IIC01 (void) { }

/*
 * INT_SRE0/INT_TM01H (0x22)
 */
void INT_TM01H (void) { }
//void INT_SRE0 (void) { }

/*
 * INT_CSI10/INT_IIC10/INT_ST1 (0x24)
 */
void INT_ST1 (void) { }
//void INT_CSI10 (void) { }
//void INT_IIC10 (void) { }

/*
 * INT_CSI11/INT_IIC11/INT_SR1 (0x26)
 */
void INT_SR1 (void) { }
//void INT_CSI11 (void) { }
//void INT_IIC11 (void) { }

/*
 * INT_SRE1/INT_TM03H (0x28)
 */
void INT_TM03H (void) { }
//void INT_SRE1 (void) { }

/*
 * INT_IICA0 (0x2A)
 */
void INT_IICA0 (void) { }

/*
 * INT_TM00 (0x2C)
 */
void INT_TM00 (void) { }

/*
 * INT_TM01 (0x2E)
 */
void INT_TM01 (void) { }

/*
 * INT_TM02 (0x30)
 */
void INT_TM02 (void) { }

/*
 * INT_TM03 (0x32)
 */
void INT_TM03 (void) { }

/*
 * INT_AD (0x34)
 */
void INT_AD (void) { }

/*
 * INT_RTC (0x36)
 */
void INT_RTC (void) { }

/*
 * INT_IT (0x38)
 */
void INT_IT (void) { }

/*
 * INT_KR (0x3A)
 */
void INT_KR (void) { }

/*
 * INT_CSI30/INT_IIC30/INT_ST3 (0x3C)
 */
void INT_ST3 (void) { }
//void INT_CSI30 (void) { }
//void INT_IIC30 (void) { }

/*
 * INT_CSI31/INT_IIC31/INT_SR3 (0x3E)
 */
void INT_SR3 (void) { }
//void INT_CSI31 (void) { }
//void INT_IIC31 (void) { }

/*
 * INT_TRJ0 (0x40)
 */
void INT_TRJ0 (void) { }

/*
 * INT_TM10 (0x42)
 */
void INT_TM10 (void) { }

/*
 * INT_TM11 (0x44)
 */
void INT_TM11 (void) { }

/*
 * INT_TM12 (0x46)
 */
void INT_TM12 (void) { }

/*
 * INT_TM13 (0x48)
 */
void INT_TM13 (void) { }

/*
 * INT_P6 (0x4A)
 */
void INT_P6 (void) { }

/*
 * INT_P7 (0x4C)
 */
void INT_P7 (void) { }

/*
 * INT_P8 (0x4E)
 */
void INT_P8 (void) { }

/*
 * INT_P9 (0x50)
 */
void INT_P9 (void) { }

/*
 * INT_CMP0/INT_P10 (0x52)
 */
void INT_P10 (void) { }
//void INT_CMP0 (void) { }

/*
 * INT_CMP1/INT_P11 (0x54)
 */
void INT_P11 (void) { }
//void INT_CMP1 (void) { }

/*
 * INT_TRD0 (0x56)
 */
void INT_TRD0 (void) { }

/*
 * INT_TRD1 (0x58)
 */
void INT_TRD1 (void) { }

/*
 * INT_TRG (0x5A)
 */
void INT_TRG (void) { }

/*
 * INT_SRE3/INT_TM13H (0x5C)
 */
void INT_TM13H (void) { }
//void INT_SRE3 (void) { }

/*
 * INT_IICA1 (0x60)
 */
void INT_IICA1 (void) { }

/*
 * INT_FL (0x62)
 */
void INT_FL (void) { }

/*
 * INT_BRK_I (0x7E)
 */
void INT_BRK_I (void) { }
