/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  RTOSDemo                                       */
/*      FILE         :  interrupt_handlers.c                           */
/*      DESCRIPTION  :  Interrupt Handler                              */
/*      CPU SERIES   :  RL78 - G1C                                     */
/*      CPU TYPE     :  R5F10JBC                                       */
/*  													               */
/*      This file is generated by e2studio.                        */
/*  													               */
/***********************************************************************/                                                                       
                                                                                   
#include "interrupt_handlers.h"

/*
 * INT_SRO/INT_WDTI (0x4)
 */
void INT_WDTI (void) { }
//void INT_SRO (void) { }

/*
 * INT_LVI (0x6)
 */
void INT_LVI (void) { }

/*
 * INT_P0 (0x8)
 */
void INT_P0 (void) { }

/*
 * INT_P1 (0xA)
 */
void INT_P1 (void) { }

/*
 * INT_P2 (0xC)
 */
void INT_P2 (void) { }

/*
 * INT_P3 (0xE)
 */
void INT_P3 (void) { }

/*
 * INT_P4 (0x10)
 */
void INT_P4 (void) { }

/*
 * INT_P5 (0x12)
 */
void INT_P5 (void) { }

/*
 * INT_DMA0 (0x1A)
 */
void INT_DMA0 (void) { }

/*
 * INT_DMA1 (0x1C)
 */
void INT_DMA1 (void) { }

/*
 * INT_CSI00/INT_IIC00/INT_ST0 (0x1E)
 */
void INT_ST0 (void) { }
//void INT_CSI00 (void) { }
//void INT_IIC00 (void) { }

/*
 * INT_TM00 (0x20)
 */
void INT_TM00 (void) { }

/*
 * INT_CSI01/INT_IIC01/INT_SR0 (0x22)
 */
void INT_SR0 (void) { }
//void INT_CSI01 (void) { }
//void INT_IIC01 (void) { }

/*
 * INT_SRE0/INT_TM01H (0x24)
 */
void INT_TM01H (void) { }
//void INT_SRE0 (void) { }

/*
 * INT_TM03H (0x2A)
 */
void INT_TM03H (void) { }

/*
 * INT_IICA0 (0x2C)
 */
void INT_IICA0 (void) { }

/*
 * INT_TM01 (0x2E)
 */
void INT_TM01 (void) { }

/*
 * INT_TM02 (0x30)
 */
void INT_TM02 (void) { }

/*
 * INT_TM03 (0x32)
 */
void INT_TM03 (void) { }

/*
 * INT_AD (0x34)
 */
void INT_AD (void) { }

/*
 * INT_RTC (0x36)
 */
void INT_RTC (void) { }

/*
 * INT_IT (0x38)
 */
void INT_IT (void) { }

/*
 * INT_USB (0x3C)
 */
void INT_USB (void) { }

/*
 * INT_RSUM (0x3E)
 */
void INT_RSUM (void) { }

/*
 * INT_P8 (0x4E)
 */
void INT_P8 (void) { }

/*
 * INT_P9 (0x50)
 */
void INT_P9 (void) { }

/*
 * INT_MD (0x5E)
 */
void INT_MD (void) { }

/*
 * INT_FL (0x62)
 */
void INT_FL (void) { }

/*
 * INT_BRK_I (0x7E)
 */
void INT_BRK_I (void) { }
