[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"RDK_Jlink" 
[CONFIGURATIONS]
"Blinky" 
"Debug" 
"Debug-with-optimisation" 
[CURRENT_CONFIGURATION]
"Blinky" 
[CURRENT_SESSION]
"RDK_Jlink" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_Blinky]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Blinky]
"RDK_Jlink" 
[GENERAL_DATA_CONFIGURATION_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Debug]
"RDK_Jlink" 
[GENERAL_DATA_CONFIGURATION_Debug-with-optimisation]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Debug-with-optimisation]
"RDK_Jlink" 
[GENERAL_DATA_CONFIGURATION_SESSION_Debug-with-optimisation_RDK_Jlink]
[GENERAL_DATA_SESSION_RDK_Jlink]
[GENERAL_DATA_CONFIGURATION_SESSION_Blinky_RDK_Jlink]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_RDK_Jlink]
[END]
