/* Methods to run manually (for ABBU only) */

Method(lf00) { IIN0() mf00() Return(POUT) }
Method(lf01) { IIN0() mf01() Return(POUT) }
Method(lf02) { IIN0() mf02() Return(POUT) }
Method(lf03) { IIN0() mf03() Return(POUT) }
Method(lf04) { IIN0() mf04() Return(POUT) }
Method(lf05) { IIN0() mf05() Return(POUT) }
Method(lf06) { IIN0() mf06() Return(POUT) }
Method(lf07) { IIN0() mf07() Return(POUT) }
Method(lf08) { IIN0() mf08() Return(POUT) }
Method(lf09) { IIN0() mf09() Return(POUT) }
Method(lf0a) { IIN0() mf0a() Return(POUT) }
Method(lf0b) { IIN0() mf0b() Return(POUT) }
Method(lf0c) { IIN0() mf0c() Return(POUT) }
Method(lf0d) { IIN0() mf0d() Return(POUT) }
Method(lf0e) { IIN0() mf0e() Return(POUT) }
Method(lf0f) { IIN0() mf0f() Return(POUT) }
Method(lf10) { IIN0() mf10() Return(POUT) }
Method(lf11) { IIN0() mf11() Return(POUT) }
Method(lf12) { IIN0() mf12() Return(POUT) }
Method(lf13) { IIN0() mf13() Return(POUT) }
Method(lf14) { IIN0() mf14() Return(POUT) }
Method(lf15) { IIN0() mf15() Return(POUT) }
Method(lf16) { IIN0() mf16() Return(POUT) }
Method(lf17) { IIN0() mf17() Return(POUT) }
Method(lf18) { IIN0() mf18() Return(POUT) }
Method(lf19) { IIN0() mf19() Return(POUT) }
Method(lf1a) { IIN0() mf1a() Return(POUT) }
Method(lf1b) { IIN0() mf1b() Return(POUT) }
Method(lf1c) { IIN0() mf1c() Return(POUT) }
Method(lf1d) { IIN0() mf1d() Return(POUT) }
Method(lf1e) { IIN0() mf1e() Return(POUT) }
Method(lf1f) { IIN0() mf1f() Return(POUT) }
Method(lf20) { IIN0() mf20() Return(POUT) }
Method(lf21) { IIN0() mf21() Return(POUT) }
Method(lf22) { IIN0() mf22() Return(POUT) }
Method(lf23) { IIN0() mf23() Return(POUT) }
Method(lf24) { IIN0() mf24() Return(POUT) }
Method(lf25) { IIN0() mf25() Return(POUT) }
Method(lf26) { IIN0() mf26() Return(POUT) }
Method(lf27) { IIN0() mf27() Return(POUT) }
Method(lf28) { IIN0() mf28() Return(POUT) }
Method(lf29) { IIN0() mf29(0) Return(POUT) }
Method(lf2a) { IIN0() mf2a(0) Return(POUT) }
Method(lf2b) { IIN0() mf2b() Return(POUT) }
Method(lf2c) { IIN0() mf2c(0) Return(POUT) }
Method(lf2d) { IIN0() mt0e() Return(POUT) }
